import { UserStats, AssignedUser, Language, FoodCombo } from './types';

export const INDIAN_LANGUAGES: Language[] = [
  'English', 'Assamese', 'Bengali', 'Bodo', 'Dogri', 'Gujarati', 
  'Hindi', 'Kannada', 'Kashmiri', 'Konkani', 'Maithili', 'Malayalam', 
  'Manipuri', 'Marathi', 'Nepali', 'Odia', 'Punjabi', 'Sanskrit', 
  'Santali', 'Sindhi', 'Tamil', 'Telugu', 'Urdu'
];

export const MAIN_LANGUAGES: Language[] = ['English', 'Hindi', 'Gujarati'];

export const INITIAL_USER_STATS: UserStats = {
  calories: { current: 0, target: 0 },
  protein: { current: 0, target: 0 },
  carbs: { current: 0, target: 0 },
  fats: { current: 0, target: 0 },
  fiber: { current: 0, target: 0 },
  hydration: { current: 0, target: 0 },
  exercise: {
    caloriesBurnt: 0,
    logs: []
  },
  meals: [],
  checkIns: [
    { id: 'green_tea', label: 'Green Tea', checked: false },
    { id: 'shakes', label: 'Shakes', checked: false }
  ],
  supplements: [],
  energyLevel: 5,
  targetEnergyLevel: 8,
  weight: 0
};

export const MOCK_ASSIGNED_USERS: AssignedUser[] = [
  {
    id: 'user_1',
    name: 'Rahul Sharma',
    avatar: 'https://i.pravatar.cc/150?u=user_1',
    lastLog: '2 hours ago',
    status: 'optimal',
    weight: 75.5,
    targetWeight: 72.0,
    coachId: 'coach_sarah',
    stats: {
      ...INITIAL_USER_STATS,
      calories: { current: 1850, target: 2200 },
      protein: { current: 120, target: 150 },
      carbs: { current: 200, target: 250 },
      fats: { current: 65, target: 75 },
      fiber: { current: 22, target: 30 },
      hydration: { current: 2.5, target: 3.5 },
      energyLevel: 8,
      meals: []
    }
  },
  {
    id: 'user_2',
    name: 'Priya Patel',
    avatar: 'https://i.pravatar.cc/150?u=user_2',
    lastLog: '5 hours ago',
    status: 'low-fiber',
    weight: 62.0,
    targetWeight: 60.0,
    coachId: 'coach_sarah',
    stats: {
      ...INITIAL_USER_STATS,
      calories: { current: 1200, target: 1800 },
      protein: { current: 80, target: 120 },
      carbs: { current: 150, target: 200 },
      fats: { current: 40, target: 60 },
      fiber: { current: 12, target: 25 },
      hydration: { current: 1.5, target: 2.5 },
      energyLevel: 6,
      meals: [
        { id: 'm3', name: 'Paneer Tikka', kcal: 450, protein: 25, carbs: 10, fats: 35, fiber: 2, time: '02:00 PM' }
      ]
    }
  },
  {
    id: 'user_3',
    name: 'Amit Singh',
    avatar: 'https://i.pravatar.cc/150?u=user_3',
    lastLog: '1 day ago',
    status: 'incomplete',
    weight: 88.4,
    targetWeight: 85.0,
    coachId: 'coach_mike',
    stats: {
      ...INITIAL_USER_STATS,
      calories: { current: 2100, target: 2500 },
      protein: { current: 140, target: 180 },
      carbs: { current: 250, target: 300 },
      fats: { current: 70, target: 85 },
      fiber: { current: 25, target: 35 },
      hydration: { current: 3.0, target: 4.0 },
      energyLevel: 7,
      meals: []
    }
  }
];

export const MOCK_COACHES = [
  { id: 'coach_sarah', name: 'Coach Sarah', avatar: 'https://i.pravatar.cc/150?u=coach_sarah' },
  { id: 'coach_mike', name: 'Coach Mike', avatar: 'https://i.pravatar.cc/150?u=coach_mike' },
];

export const FOOD_COMBOS: FoodCombo[] = [];

export const MOCK_USER_STATS = INITIAL_USER_STATS;

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  'English': {
    'welcome': 'Welcome back',
    'privacy_note': 'Your privacy and security are our top priorities. Please select your role to continue.',
    'enter_user': 'Enter as User',
    'enter_coach': 'Enter as Coach',
    'enter_owner': 'Enter as Owner',
    'user_desc': 'Track your health, log meals, and stay active.',
    'coach_desc': 'Manage your clients and provide health guidance.',
    'owner_desc': 'Full system access and management.',
    'secure_auth': 'Secure Authentication',
    'id_pin': 'Account ID or PIN',
    'confirm_continue': 'Confirm & Continue',
    'forgot_pin': 'Forgot your ID or PIN?',
    'daily_motivation': 'Daily Motivation',
    'daily_calories': 'Daily Calories',
    'protein': 'Protein',
    'carbs': 'Carbs',
    'fats': 'Fats',
    'fiber': 'Fiber',
    'stay_hydrated': 'Stay Hydrated',
    'add_water': 'Add 250ml',
    'health_snapshot': 'Daily Update',
    'steps_today': 'Steps Today',
    'sleep_quality': 'Sleep Quality',
    'log_meal': 'Add what you did',
    'add_what_you_did': 'Add what you did',
    'take_photo': 'Take a photo',
    'show_photo': 'Show a photo',
    'meal_placeholder': 'What did you eat?',
    'no_combos': 'No common meals saved yet.',
    'home': 'Home',
    'coach': 'Coach',
    'security': 'Security',
    'language': 'Language',
    'detecting': 'Seeing...',
    'live_ai': 'Live AI Analysis',
    'identify_meal': "See what's in your food",
    'confirm_save': 'Save this meal',
    'add_manual': 'Type it yourself',
    'quick_logs': 'Quick Logs',
    'view_history': 'View History',
    'coach_dashboard': 'Coach Dashboard',
    'assigned_users': 'Assigned Users',
    'active': 'Active',
    'users': 'Users',
    'active_users': 'Active Users',
    'macro_dist': 'Macro Distribution',
    'hydration': 'Hydration',
    'water_goal_prompt': 'How much water will you drink today? (in liters):',
    'set_goal': 'Set Goal',
    'current_stats': 'Current Stats',
    'target_stats': 'Target Stats',
    'pin_hint': 'Your pin must have 4 numbers',
    'setup_title': 'First Steps',
    'save_setup': 'Save and Start',
    'select_goal': 'Select your health goal',
    'food_combos': 'Common Meals',
    'add_combo': 'Add New Meal',
    'update_combo': 'Change Meal',
    'kcal': 'kcal',
    'meters': 'meters',
    'liters': 'liters',
    'distance': 'Distance',
    'km': 'km',
    'today': 'Today',
    'enter_name': 'What is your name?',
    'name_placeholder': 'Your name',
    'upload_meal': 'Show a photo',
    'analysing_meal': 'Analysing your meal...',
    'hi': 'Hi',
    'last_meal': 'Last Meal',
    'daily_meals': 'Daily Meals',
    'nutrition_details': 'Nutrition Details',
    'back_to_users': 'Back to Users',
    'long_press_hint': 'Hold to change or remove',
    'meal_name': 'Meal Name',
    'save_as_predefined': 'Save for next time',
    'update': 'Change',
    'delete': 'Remove',
    'cancel': 'Cancel',
    'save_changes': 'Save Changes',
    'close': 'Close',
    'forgot_id_user': 'Ask your coach for your ID',
    'forgot_id_coach': 'Ask developers for new ID',
    'water_goal_msg': "Today's updated water goal is",
    'edit': 'Edit',
    'set': 'Set',
    'bottles': 'bottles',
    'bottles_needed': 'bottles needed for today',
    'exercise': 'Exercise',
    'calories_burnt': 'Calories Burnt',
    'select_exercise': 'Select Exercise',
    'duration_minutes': 'Duration (minutes)',
    'log_exercise': 'Log Exercise',
    'no_exercise_logs': 'No exercises logged yet.',
    'burnt': 'burnt',
    'mins': 'mins',
    'add_exercise': 'Add Exercise',
    'add_another': 'Add Another',
    'session_summary': 'Session Summary',
    'no_exercises_added': 'No exercises added to session yet.',
    'total_duration': 'Total Duration',
    'total_calories': 'Total Calories',
    'save': 'Save',
    'exercise_history': 'Exercise History',
    'tell_us_what_ate': 'Tell us what all you ate today',
    'bmi': 'BMI',
    'underweight': 'Underweight',
    'normal': 'Normal',
    'overweight': 'Overweight',
    'obese': 'Obese',
    'weight_tracking': 'Weight Tracking',
    'weight_history': 'Weight History',
    'log_weight': 'Log Weight',
    'current_weight': 'Current Weight',
    'weight_change': 'Weight Change',
    'recent_meals': 'Recent Meals',
    'no_meals_yet': 'No meals logged',
    'check_in_title': 'Daily Check-in',
    'green_tea': 'Green Tea',
    'shakes': 'Shakes',
    'supplements': 'Supplements',
    'profile': 'Profile',
    'settings': 'Settings',
    'food': 'Food',
    'personal_tracking': 'Personal Tracking',
    'energy_level': 'Energy Level',
    'how_is_energy': 'How is your energy today?',
    'low': 'Low',
    'medium': 'Medium',
    'high': 'High',
    'system_overview': 'System Overview',
    'manage_users': 'Manage Users',
    'manage_coaches': 'Manage Coaches',
    'create_account': 'Create Account',
    'assign_coach': 'Assign Coach',
    'promote_to_coach': 'Promote to Coach',
    'remove_coach': 'Remove Coach',
    'delete_user': 'Delete User',
    'are_you_sure': 'Are you sure?',
    'action_irreversible': 'This action cannot be undone.',
    'confirm': 'Confirm',
    'role': 'Role',
    'pin': 'PIN',
    'account_id': 'Account ID',
    'member': 'Member',
    'coach_label': 'Coach',
    'no_coach': 'No Coach Assigned',
    'select_coach': 'Select a Coach',
  },
  'Hindi': {
    'welcome': 'वापसी पर स्वागत है',
    'privacy_note': 'आपकी गोपनीयता और सुरक्षा हमारी सर्वोच्च प्राथमिकताएं हैं। कृपया जारी रखने के लिए अपनी भूमिका चुनें।',
    'enter_user': 'उपयोगकर्ता के रूप में प्रवेश करें',
    'enter_coach': 'कोच के रूप में प्रवेश करें',
    'enter_owner': 'मालिक के रूप में प्रवेश करें',
    'user_desc': 'अपने स्वास्थ्य को ट्रैक करें, भोजन लॉग करें और सक्रिय रहें।',
    'coach_desc': 'अपने ग्राहकों को प्रबंधित करें और स्वास्थ्य मार्गदर्शन प्रदान करें।',
    'owner_desc': 'पूर्ण सिस्टम एक्सेस और प्रबंधन।',
    'secure_auth': 'सुरक्षित प्रमाणीकरण',
    'id_pin': 'खाता आईडी या पिन',
    'confirm_continue': 'पुष्टि करें और जारी रखें',
    'forgot_pin': 'अपना आईडी या पिन भूल गए?',
    'daily_motivation': 'दैनिक प्रेरणा',
    'fun_food_fact': 'मजेदार भोजन तथ्य',
    'daily_calories': 'दैनिक कैलोरी',
    'protein': 'प्रोटीन',
    'carbs': 'कार्ब्स',
    'fats': 'वसा',
    'fiber': 'फाइबर',
    'stay_hydrated': 'हाइड्रेटेड रहें',
    'add_water': 'पानी जोड़ें',
    'health_snapshot': 'दैनिक अपडेट',
    'steps_today': 'आज के कदम',
    'sleep_quality': 'नींद की गुणवत्ता',
    'log_meal': 'जो आपने किया उसे जोड़ें',
    'add_what_you_did': 'जो आपने किया उसे जोड़ें',
    'take_photo': 'फोटो लें',
    'show_photo': 'फोटो दिखाएं',
    'meal_placeholder': 'आपने क्या खाया?',
    'no_combos': 'अभी तक कोई सामान्य भोजन सहेजा नहीं गया है।',
    'home': 'होम',
    'coach': 'कोच',
    'language': 'भाषा',
    'detecting': 'देख रहा है...',
    'live_ai': 'लाइव एआई विश्लेषण',
    'identify_meal': 'अपने भोजन में क्या है देखें',
    'confirm_save': 'इस भोजन को सहेजें',
    'add_manual': 'स्वयं टाइप करें',
    'quick_logs': 'त्वरित लॉग',
    'view_history': 'इतिहास देखें',
    'coach_dashboard': 'कोच डैशबोर्ड',
    'assigned_users': 'सौंपे गए उपयोगकर्ता',
    'active': 'सक्रिय',
    'users': 'उपयोगकर्ता',
    'active_users': 'सक्रिय उपयोगकर्ता',
    'macro_dist': 'मैक्रो वितरण',
    'hydration': 'हाइड्रेशन',
    'water_goal_prompt': 'आज आप कितना पानी पिएंगे? (लीटर में):',
    'set_goal': 'लक्ष्य निर्धारित करें',
    'current_stats': 'वर्तमान आँकड़े',
    'target_stats': 'लक्ष्य आँकड़े',
    'pin_hint': 'आपके पिन में 4 अंक होने चाहिए',
    'setup_title': 'पहले कदम',
    'save_setup': 'सहेजें और शुरू करें',
    'food_combos': 'सामान्य भोजन',
    'add_combo': 'नया भोजन जोड़ें',
    'update_combo': 'भोजन बदलें',
    'kcal': 'किलो कैलोरी',
    'meters': 'मीटर',
    'liters': 'लीटर',
    'distance': 'दूरी',
    'km': 'किमी',
    'today': 'आज',
    'analysing_meal': 'भोजन का विश्लेषण किया जा रहा है...',
    'daily_meals': 'दैनिक भोजन',
    'long_press_hint': 'बदलने या हटाने के लिए दबाकर रखें',
    'meal_name': 'भोजन का नाम',
    'save_as_predefined': 'अगली बार के लिए सहेजें',
    'update': 'बदलें',
    'delete': 'हटाएं',
    'cancel': 'रद्द करें',
    'save_changes': 'परिवर्तन सहेजें',
    'close': 'बंद करें',
    'forgot_id_user': 'आईडी के लिए अपने कोच से पूछें',
    'forgot_id_coach': 'नई आईडी के लिए डेवलपर्स से पूछें',
    'water_goal_msg': 'आज का अपडेटेड पानी का लक्ष्य है',
    'edit': 'संपादन',
    'set': 'सेट करें',
    'bottles': 'बोतलें',
    'bottles_needed': 'आज के लिए आवश्यक बोतलें',
    'exercise': 'व्यायाम',
    'calories_burnt': 'कैलोरी जली',
    'select_exercise': 'व्यायाम चुनें',
    'duration_minutes': 'अवधि (मिनट)',
    'log_exercise': 'व्यायाम लॉग करें',
    'no_exercise_logs': 'अभी तक कोई व्यायाम लॉग नहीं किया गया है।',
    'burnt': 'जली',
    'mins': 'मिनट',
    'add_exercise': 'व्यायाम जोड़ें',
    'add_another': 'एक और जोड़ें',
    'session_summary': 'सत्र सारांश',
    'no_exercises_added': 'अभी तक सत्र में कोई व्यायाम नहीं जोड़ा गया है।',
    'total_duration': 'कुल अवधि',
    'total_calories': 'कुल कैलोरी',
    'save': 'सहेजें',
    'exercise_history': 'व्यायाम इतिहास',
    'tell_us_what_ate': 'हमें बताएं कि आपने आज क्या खाया',
    'bmi': 'बीएमआई',
    'underweight': 'कम वजन',
    'normal': 'सामान्य',
    'overweight': 'अधिक वजन',
    'obese': 'मोटापा',
    'weight_tracking': 'वजन ट्रैकिंग',
    'weight_history': 'वजन इतिहास',
    'log_weight': 'वजन लॉग करें',
    'current_weight': 'वर्तमान वजन',
    'weight_change': 'वजन परिवर्तन',
    'recent_meals': 'हाल का भोजन',
    'no_meals_yet': 'कोई भोजन लॉग नहीं किया गया है',
    'check_in_title': 'दैनिक चेक-इन',
    'green_tea': 'ग्रीन टी',
    'shakes': 'शेक',
    'supplements': 'सप्लीमेंट्स',
    'profile': 'प्रोफ़ाइल',
    'settings': 'सेटिंग्स',
    'food': 'भोजन',
    'energy_level': 'ऊर्जा स्तर',
    'how_is_energy': 'आज आपकी ऊर्जा कैसी है?',
    'low': 'कम',
    'medium': 'मध्यम',
    'high': 'उच्च',
  },
  'Assamese': { 'welcome': 'স্বাগতম' },
  'Bengali': { 'welcome': 'স্বাগতম' },
  'Bodo': { 'welcome': 'बरायবায়' },
  'Dogri': { 'welcome': 'जी आयां नूं' },
  'Gujarati': { 'welcome': 'સ્વાગત છે' },
  'Kannada': { 'welcome': 'ಸ್ವಾಗತ' },
  'Kashmiri': { 'welcome': 'خوش آمدید' },
  'Konkani': { 'welcome': 'येवकार' },
  'Maithili': { 'welcome': 'स्वागत अछि' },
  'Malayalam': { 'welcome': 'സ്വാഗതം' },
  'Manipuri': { 'welcome': 'তরাম্না ওকচরি' },
  'Marathi': { 'welcome': 'स्वागत आहे' },
  'Nepali': { 'welcome': 'स्वागत छ' },
  'Odia': { 'welcome': 'ସ୍ୱାଗତ' },
  'Punjabi': { 'welcome': 'ਜੀ ਆਇਆਂ ਨੂੰ' },
  'Sanskrit': { 'welcome': 'स्वागतम्' },
  'Santali': { 'welcome': 'ᱥᱟᱜᱩᱱ ᱫᱟᱨᱟᱢ' },
  'Sindhi': { 'welcome': 'ڀلي ڪري ਆਇਆ' },
  'Tamil': { 'welcome': 'வரவேற்கிறோம்' },
  'Telugu': { 'welcome': 'స్వాగతం' },
  'Urdu': { 'welcome': 'خوش آمدید' },
};

export const EXERCISES = [
  { name: 'Walking', met: 3.5 },
  { name: 'Running', met: 8.0 },
  { name: 'Cycling', met: 8.0 },
  { name: 'Swimming', met: 7.0 },
  { name: 'Yoga', met: 2.5 },
  { name: 'Weight Lifting', met: 3.5 },
  { name: 'Jumping Rope', met: 11.0 },
  { name: 'HIIT', met: 8.0 },
  { name: 'Dancing', met: 4.5 },
  { name: 'Pilates', met: 3.0 },
];

export const MOTIVATIONS = [
  "Small steps lead to big changes. Keep going!",
  "Your body is a temple, but only if you treat it like one.",
  "Health is not about the weight you lose, but the life you gain.",
  "The only bad workout is the one that didn't happen.",
  "Consistency is the key to success. You've got this!",
  "Focus on progress, not perfection.",
  "Your future self will thank you for the effort you put in today."
];

export const FOOD_FACTS = [
  "Apples are more effective at waking you up in the morning than coffee.",
  "Broccoli contains more protein per calorie than steak.",
  "Honey is the only food that doesn't spoil. It can last for thousands of years!",
  "Bananas are berries, but strawberries aren't.",
  "Avocados have more potassium than bananas.",
  "Drinking water can boost your metabolism by 24-30% over 1-1.5 hours.",
  "Dark chocolate is loaded with nutrients that can positively affect your health."
];
